Donnachie_ICD10gm.html: Donnachie_ICD10gm.Rmd \
	style.css
	R -e "rmarkdown::render('Donnachie_ICD10gm.Rmd')"
	sudo -u donnachie.net cp -f Donnachie_ICD10gm.html /var/www/vhosts/donnachie.net/httpdocs/drafts/

