# ICD10gm

An R Package for Working with the German Modification of the International Statistical Classification of Diseases and Related Health Problems

The ICD-10 classification of diseases and related health problems (ICD-10) is an international standard for the coding of health service data. In Germany the [German Instutite of Medical Documentation and Information (DIMDI)](https://www.dimdi.de/static/en/dimdi/index.htm) releases a German Modification (ICD-10-GM) of the classification that forms a compulsory part of all remuneration claims in the ambulatory and hospital sectors.

This package was created to facilitate the analysis of data coded using the ICD-10-GM. In particular, it has three aims:

1. To provide convenient to the extended ICD-10-GM metadata
2. To facilitate the specification of ICD codes for analysis, utilising the ICD hierarchy (e.g. given the specification "A0" return all subcodes in the range "A01" to "A09")
3. To enable the historization of ICD specifications by applying the automatic code transitions provided by DIMDI and identifying potentially problematic codes

ICD10gm is designed for use in the context of medical and health services research using routinely collected claims data. It is not suitable for use in operative coding as it does not include all relevant metadata (e.g. inclusion and exclusion notes and the detailed definitions of psychiatric diagnoses). The metadata provided in the ICD10gm package is not intended to replace the [official DIMDI documentation](https://www.dimdi.de/static/en/klassi/icd-10-gm/index.htm), which should always be consulted when specifying ICD codes for analysis.

The packge is functional and is in active use, but minor bugs may be present. In preparation for a possible CRAN release, current effort is focussed on documentation and minor convenience features.

## Getting Started

The package is not (yet) available from CRAN but can be installed from github as follows:

```{r eval = FALSE}
# Install the devtools package if not already installed
if (!("devtools" %in% .packages(all.available=TRUE))) install.package("devtools")

# Install ICD10gm package from github
devtools::install_github("edonnache/ICD10gm")
```

## Basic Use

### Access ICD-10-GM metadata 

The ICD-10-GM metadata are provided by four data.frames that form the core of the ICD10gm package:

- `icd_meta_chapters`: Specification of the ICD-10-GM chapters with label and number (Arabic and Roman numerals)
- `icd_meta_blocks`: Specification of the ICD-10 blocks, each containing a sequence of related ICD-10 codes
- `icd_meta_codes`: Extended metadata for all ICD-10-GM codes
- `icd_meta_transitions`: The "crosswalk" table specifying old and new ICD-10-GM codes for successive annual versions.

N.B. While column names have been translated into English, the ICD-10-GM labels are written in German.

### Utility functions

Several utility functions are provided to perform common queries on the metadata:

- `get_icd_labels` queries `icd_meta_codes` and returns only the ICD subcodes and labels for specified codes and years.
- `get_icd_history` queries `icd_meta_transitions` and returns only the mappings for specified codes and years.
- `icd_showchanges` and `icd_showchanges_icd3` query `icd_meta_transitions` and return entries that are affected by changes in the ICD-10-GM versions.
 
### Expand a ICD specification down the hierarchy

The function `icd_expand` takes a data.frame containing ICD codes and optional metadata as input. It returns a data.frame containing all ICD codes at or below the specified level of the hierarchy (e.g. the specification "E11" is expanded to include all three, four and five-digit codes beginning with E11). Expansion is done within a specified version of the ICD-10-GM (e.g. year 2018).

### Historise an ICD specification

The function `icd_history` takes the result of `icd_expand`, specified for a particular year, and returns a data.frame containing all corresponding codes for the specified years (from 2003). To do this, it applies the ICD-10-GM transition tables to map codes between successive ICD-10-GM versions. Only automatic transitions are followed.


## Copyright

The underlying ICD-10-GM metadata is copyright of the [German Instutite of Medical Documentation and Information (DIMDI)](https://www.dimdi.de/static/en/dimdi/index.htm). The source files are available free of charge from the [DIMDI Download Centre](http://www.dimdi.de/dynamic/de/klassi/downloadcenter/). I believe that their use in this package is compatible with the copyright restrictions. In particular:

- The distribution of an "added-value product" derived from the original DIMDI classification files is expressly permitted.

- Distribution of the original classification files is forbidden. Consequently, this package distributes only the code required to process these files. Those wishing to compile the data from scratch must download the files from the DIMDI download centre and agree to the copyright restrictions.

- The package does not modify the ICD-10-GM codes, texts or other metadata in any way other than to restructure the data into a convenient form.

- The package does not contain any commercial advertising.

- The source of the data is clearly stated, both here and in the package documentation.



## Related Packages

The [icd package](https://cran.r-project.org/web/packages/icd/) on CRAN has similar aims but has a slightly different approach and focusses on the US version of the ICD-10 system.
