#' Historize a list of ICD codes to cover the specified years
#' @param icd_expand A data.frame (e.g. as generated by the function icd_expand)
#' @param years Years to historize (e.g. 2005:2014)
#' @return data.frame with columns YEAR, ICD_CODE, ICD_COMPRESSED, ICD_LABEL and, if specified, DIAG_GROUP
#' @export
icd_history <- function(icd_expand, years){
  icd_hist <- ICD10gm::icd_meta_transition[,
    c("year_from", "year_to",
      "icd_from", "icd_to",
      "automatic_forward", "automatic_backward")]

	stopifnot(
						all(grepl("^\\d{4}$", years)),
						all(years %in% unique(c(icd_hist$year_to, icd_hist$year_from))),
						all(c("year", "icd_code") %in% names(icd_expand))
						)

  # We are not in the tidyverse!
  # Make sure icd_expand is not a tibble,
  # otherwise merge might return error
  # (shoud be fixed in current tibble versions, but better safe than sorry)
  icd_expand <- as.data.frame(icd_expand)

	icd_back <- function(icd_expand, icd_hist){
		out <- merge(
		  icd_expand,
		  subset(icd_hist, automatic_backward == "A"),
			by.x = c("year", "icd_code"),
			by.y = c("year_to", "icd_to"),
			all.x = TRUE, all.y = FALSE)

		# Replace YEAR with year_from
		# and ICD_CODE with icd_from
		out <- out[, which(!(names(out) %in% c("year", "icd_code")))]
		names(out)[which(names(out) == "year_from")] <- "year"
		names(out)[which(names(out) == "icd_from")] <- "icd_code"
		# out <- merge(out, ICD10gm::icd_meta_codes[, c("year", "icd_code", "icd_normcode", "icd_sub", "icd3", "label")])
		out <- out[, names(icd_expand)]
		return(unique(out))
	}

	icd_forward <- function(icd_expand, icd_hist){
		out <- merge(icd_expand,
		             subset(icd_hist, automatic_forward == TRUE),
					by.x = c("year", "icd_code"),
					by.y = c("year_from", "icd_from"),
					all.x = TRUE, all.y = FALSE)

		# Replace YEAR with year_to
		# and ICD_CODE with icd_to
		out <- out[, which(!(names(out) %in% c("year", "icd_code")))]
		names(out)[which(names(out) == "year_to")] <- "year"
		names(out)[which(names(out) == "icd_to")] <- "icd_code"
		out <- out[, names(icd_expand)]
		return(unique(out))
	}

	# Determine starting year from input data
	year_init <- icd_expand[1, "year"]

	# Initialise output list
	icd_hist_out <- list()
	icd_hist_out[[as.character(year_init)]] <- icd_expand

	# Historise each year in vector years prior to starting year
	years_back <- years[years < year_init]
	for (y in sort(years_back, decreasing = TRUE)){
		icd_hist_out[[as.character(y)]] <-
			icd_back(icd_hist_out[[as.character(y+1)]],
							 icd_hist)
	}

	# Historise each year in vector years subsequent to starting year
	years_forward<- years[years > year_init]
	for (y in years_forward){
		icd_hist_out[[as.character(y)]] <-
			icd_forward(icd_hist_out[[as.character(y-1)]],
									icd_hist)
	}

	# Return data frame with alternative coding for the ICD
	# (without ".", e.g. for InBA grouper)
	out <- subset(do.call("rbind", icd_hist_out), !is.na(year))
	out$year <- as.integer(out$year)
	return(out)
}
