#' Historize a list of ICD codes to cover the specified years
#' @param icd_expand A data.frame (e.g. as generated by the function icd_expand)
#' @param years Years to historize (e.g. 2005:2014)
#' @return data.frame with columns YEAR, ICD_CODE, ICD_COMPRESSED, ICD_LABEL and, if specified, DIAG_GROUP
#' @export
icd_history <- function(icd_expand, years){
	stopifnot(
						all(grepl("^\\d{4}$", years)),
						all(years %in% icd_hist$YEAR),
						all(c("YEAR", "ICD_CODE") %in% names(icd_expand))
						)

	icd_back <- function(icd_expand, icd_hist){
		out <- merge(icd_expand, icd_hist,
					by.x = c("YEAR", "ICD_CODE"),
					by.y = c("year_to", "icd_to"),
					all.x = TRUE, all.y = FALSE)

		# Replace YEAR with year_from
		# and ICD_CODE with icd_from
		out <- out[, which(!(names(out) %in% c("YEAR", "ICD_CODE")))]
		names(out)[which(names(out) == "year_from")] <- "YEAR"
		names(out)[which(names(out) == "icd_from")] <- "ICD_CODE"
		out <- out[, names(icd_expand)]
		return(unique(out))
	}

	icd_forward <- function(icd_expand, icd_hist){
		out <- merge(icd_expand, icd_hist,
					by.x = c("YEAR", "ICD_CODE"),
					by.y = c("year_from", "icd_from"),
					all.x = TRUE, all.y = FALSE)

		# Replace YEAR with year_to
		# and ICD_CODE with icd_to
		out <- out[, which(!(names(out) %in% c("YEAR", "ICD_CODE")))]
		names(out)[which(names(out) == "year_to")] <- "YEAR"
		names(out)[which(names(out) == "icd_to")] <- "ICD_CODE"
		out <- out[, names(icd_expand)]
		return(unique(out))
	}

	# Determine starting year from input data
	year_init <- icd_expand[1, "YEAR"]

	# Initialise output list
	icd_hist_out <- list()
	icd_hist_out[[as.character(year_init)]] <- icd_expand

	# Historise each year in vector years prior to starting year
	years_back <- years[years < year_init]
	for (y in sort(years_back, decreasing = TRUE)){
		icd_hist_out[[as.character(y)]] <-
			icd_back(icd_hist_out[[as.character(y+1)]],
							 icd_hist)
	}

	# Historise each year in vector years subsequent to starting year
	years_forward<- years[years > year_init]
	for (y in years_forward){
		icd_hist_out[[as.character(y)]] <-
			icd_forward(icd_hist_out[[as.character(y-1)]],
									icd_hist)
	}

	# Return data frame with alternative coding for the ICD
	# (without ".", e.g. for InBA grouper)
	out <- subset(do.call("rbind", icd_hist_out), !is.na(YEAR))
	out$ICD_COMPRESSED <- sub("\\.", "", out$ICD_CODE)
	out$YEAR <- as.integer(out$YEAR)
	return(out)
}
